--OneToMany

DROP TABLE "Order";
DROP TABLE Customer;


SELECT *FROM Customer;
SELECT *FROM "Order";

--Родительская таблица
CREATE TABLE Customer
(
    customer_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name        CHAR(50) NOT NULL,
    email      char(50) NOT NULL UNIQUE
);
INSERT INTO Customer (NAME, EMAIL) VALUES ('Piter','piter@mail.ru');
INSERT INTO Customer (NAME, EMAIL) VALUES ('Piter1','piter1@mail.ru');
INSERT INTO Customer (NAME, EMAIL) VALUES ('Piter2','piter2@mail.ru');
INSERT INTO Customer (NAME, EMAIL) VALUES ('Piter3','pite3@mail.ru');
INSERT INTO Customer (NAME, EMAIL) VALUES ('Piter4','piter4@mail.ru');

--Дочерняя таблица, т.к. есть внешний ключ - связь с др. таблицей
CREATE TABLE "Order"
(
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    customer_id int NOT NULL REFERENCES Customer (customer_id) ,
    order_name  CHAR(50) NOT NULL,
    date_order DATE NOT NULL
);

INSERT INTO "Order" (customer_id, order_name,date_order) VALUES (1,'lemon', '11-Sep-2024 11:02:00');
INSERT INTO "Order" (customer_id, order_name, date_order) VALUES (1,'product', '11-Sep-2024 11:02:00');
INSERT INTO "Order" (customer_id, order_name, date_order) VALUES (1,'lemon', '11-Sep-2024 11:02:00');
INSERT INTO "Order" (customer_id, order_name, date_order) VALUES (1,'lemon2', '11-Sep-2024 11:02:00');
INSERT INTO "Order" (customer_id, order_name, date_order) VALUES (1,'lemon2', '11-Sep-2024 11:02:00');
INSERT INTO "Order" (customer_id, order_name, date_order) VALUES (2,'lemon', '11-Sep-2024 11:02:00');
INSERT INTO "Order" (customer_id, order_name, date_order) VALUES (3,'lemon', '11-Sep-2024 11:02:00');
INSERT INTO "Order" (customer_id, order_name, date_order) VALUES (2,'lemon', '11-Sep-2024 11:02:00');

-- объединит только пары совпадений по внешнему ключу
SELECT *FROM Customer INNER JOIN "Order"  on Customer.customer_id = "Order".customer_id;

SELECT name, order_name FROM Customer INNER JOIN "Order"  on Customer.customer_id = "Order".customer_id;

-- объединит все, т.е. всю таблицу customers, а где нет пары в таблице orders проставит null
SELECT *FROM Customer LEFT JOIN  "Order"  on Customer.customer_id = "Order".customer_id;

SELECT *FROM Customer RIGHT JOIN  "Order"  on Customer.customer_id = "Order".customer_id